### ISSUE TITLE
How to apply to long life cycle framework

### ISSUE THREAD

**Issue by DongyunLee** [litesaml/lightsaml#16]
From 2.x, I'm appling lightsaml to [Hyperf Framework](https://hyperf.wiki/2.2/#/en/).
But there are some problem because it's a long life-cycle framework based on [Swoole](https://www.php.net/manual/en/book.swoole.php).
It's void that to use classic way to get request infomations (such as `$_GET`/`$_POST`/`$_REQUEST`).

I have to use specific methods of that framework. I've always using without the *request* what inside lightsaml.

I have an idea, maybe the core library can be abstract to a more lite library who just contains core components about saml and without request.

Looking forward to your reply.

**Comment by william-suppo** [comment]
Hello @DongyunLee ,

I think to replace `symfony/http-fondation` by `psr/http-message` in this issue #20

**Comment by DongyunLee** [comment]
Sorry, I read it wrong.I thought you already implemented it😅

I think it's a good idea. Hyperf is also using `psr/http-message`.

**Comment by DongyunLee** [comment]
I'll be waiting for #20 , so close this.
