### ISSUE TITLE
Support for symfony/event-dispatcher:4.*

### ISSUE THREAD

**Issue by ankurRadicle** [litesaml/lightsaml#17]
Not able to install lightsaml in Magento due to symfony/event-dispatcher. Magento is only supporting version 4 yet of symfony/event-dispatcher.

**Comment by william-suppo** [comment]
Hello,

If you dont want, or cant, upgrade Magento, I suggest you to use an older version of the package.

Version `1.4.1` supports symfony v4 : https://packagist.org/packages/lightsaml/lightsaml#1.4.1

**Comment by ankurRadicle** [comment]
Hi
I have already upgraded Magento to the latest version and currently it is supporting symfony/event-dispatcher v4.4 and symfony/http-foundation v5.4.
Version 1.4.1 needed symfony v4.

**Comment by william-suppo** [comment]
Can you provide me your composer.json or logs after your `composer update`, I need to understand why your are stuck in v4.

**Comment by ankurRadicle** [comment]
I have added my current composer and composer lock file

[composer.docx](https://github.com/litesaml/lightsaml/files/8802985/composer.docx)
[composer_lock.docx](https://github.com/litesaml/lightsaml/files/8802987/composer_lock.docx)

**Comment by william-suppo** [comment]
Hello, I try to merge this PR next week.

**Comment by william-suppo** [comment]
It's merge. You can check v4.0.0 !
