### ISSUE TITLE
Missing 2.3.4 version

### ISSUE THREAD

**Issue by Wirone** [litesaml/lightsaml#24]
We're migrating from `lightsaml/lightsaml` to `litesaml/lightsaml` but there's no 2.3.4 version in Packagist. It's in changelog, but can't be installed.

Please add 2.3.4 tag and release this version.

**Comment by william-suppo** [comment]
Helllo, thx for your advice.

I push the tag https://github.com/litesaml/lightsaml/releases/tag/2.3.4

Bye
