### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by szepeviktor** [litesaml/lightsaml#35]
🖱️ https://github.com/litesaml/lightsaml/community/license/new?branch=master&filename=LICENSE&template=mit

Other items may need attention https://github.com/litesaml/lightsaml/community

**Comment by william-suppo** [comment]
Hello,

I push LICENSE.md on [fc8e238](https://github.com/litesaml/lightsaml/commit/fc8e2388570838e53d6127b6d7c56ced5e38d156) ;)
